Colin/mints endpoint
Shramp/mobilecoin pull request #1
Opened 2022-07-21 20:48 UTC by Shramp

### Motivation

### Future Work

[Soundtrack of this PR]()

2022-07-21 21:16 UTC, eranrund requested changes

2022-07-21 21:16 UTC, eranrund commented on mint-auditor/src/db/models/audited_mint.rs
> +    ) -> Result<Vec<AuditedMintResponse>, Error> {
I think this should just return the tuple, the http representation doesn't need to be brought into the database layer.

2022-07-21 21:16 UTC, eranrund commented on mint-auditor/src/db/models/audited_mint.rs
> +            query = query.offset(o as i64).limit(l as i64);
I think you would want to order_by something (like the id field), otherwise there's no guarantee that you'll get sane results back when paginating.
I am not a fan of implicitly ignoring offset/limit if only one is provided. Can this be broken into two if statements?

2022-07-21 21:30 UTC, Shramp commented on mint-auditor/src/db/models/audited_mint.rs
> +    ) -> Result<Vec<AuditedMintResponse>, Error> {
ah that makes sense. And that gives the service layer something to actually do

2022-07-25 17:33 UTC, david1alvarez approved these changes
LGTM!

2022-07-25 17:38 UTC, closed without merging